### ISSUE TITLE
打开http://localhost:8001/返回的是{     "detail": "Not Found" }

### ISSUE THREAD

**Issue by CharlieKoo** [aigc-apps/PAI-RAG#103]
求解，docker启动的

**Comment by moria97** [comment]
8001这个port是API服务，你可以参考这里https://github.com/aigc-apps/PAI-RAG#-api-service 直接调用8001端口的API
或者运行我们的ui镜像来配置服务：
```sh
docker run --network host -d mybigpai-public-registry.cn-beijing.cr.aliyuncs.com/mybigpai/pairag:0.0.2_ui
```

**Comment by CharlieKoo** [comment]
docker run --network host -d mybigpai-public-registry.cn-beijing.cr.aliyuncs.com/mybigpai/pairag:0.0.2_ui

这个也启动了，访问哪个url呢，8002也不行

**Comment by CharlieKoo** [comment]
访问8002就是已拒绝链接

**Comment by moria97** [comment]
> 访问8002就是已拒绝链接

可以看下ui镜像的启动日志吗？
```sh
docker logs [container_id]
```

**Comment by CharlieKoo** [comment]
![image](https://github.com/user-attachments/assets/4562928d-2b57-4519-ac9d-d6b61297afa3)

**Comment by moria97** [comment]
打开locahost:8002报错信息是什么？以及你是在什么OS上运行的呢？

**Comment by CharlieKoo** [comment]
> 打开locahost:8002报错信息是什么？以及你是在什么OS上运行的呢？
如果用--network host，那么返回503，平台是windows，我自行改成-p 8002:8002的话，能进入后台，提示
![image](https://github.com/user-attachments/assets/2d89dd43-ba57-47e9-9ce7-07ee4fdcae8d)

**Comment by moria97** [comment]
> > 打开locahost:8002报错信息是什么？以及你是在什么OS上运行的呢？
> > 如果用--network host，那么返回503，平台是windows，我自行改成-p 8002:8002的话，能进入后台，提示
> > ![image](https://private-user-images.githubusercontent.com/81978191/348060838-2d89dd43-ba57-47e9-9ce7-07ee4fdcae8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NDk0MTIsIm5iZiI6MTcyMDc0OTExMiwicGF0aCI6Ii84MTk3ODE5MS8zNDgwNjA4MzgtMmQ4OWRkNDMtYmE1Ny00N2U5LTljZTctMDdlZTRmZGNhZThkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDAxNTE1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmYTQwYjUzODM1MjY4YmE3NTBmNjAyZDY1NmJkNzEyODY1NDI3MjZmZGMyZDZjYTg0ZDdhOGVkNzQ1MzAzMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-zdVYR_bZ6R0lEAMCJcRz-u62Gi53ttOJD7kusl75tQ)

谢谢反馈，应该是docker windows版本 --net=host不支持导致，我手头暂时没有可以测试的windows 机器，你运行ui镜像的时候可以试试手动指定一下api的endpoint，比如
```
docker run --network host -d mybigpai-public-registry.cn-beijing.cr.aliyuncs.com/mybigpai/pairag:0.0.2_ui pai_rag ui -p 8002 -c http://host.docker.internal:8001/

```

**Comment by CharlieKoo** [comment]
谢谢，windows依旧需要端口映射，命令如下
`docker run -p 8002:8002 -d mybigpai-public-registry.cn-beijing.cr.aliyuncs.com/mybigpai/pairag:0.0.2_ui p
ai_rag ui -p 8002 -c http://host.docker.internal:8001/` 
建议更新一下文档

**Comment by CharlieKoo** [comment]
另有一个问题
![image](https://github.com/user-attachments/assets/248c3114-9f1c-4196-8fbc-43e62dd29d99)
lian'j链接向量数据库无法链接

**Comment by CharlieKoo** [comment]
重启已经解决该问题

> 另有一个问题 ![image](https://private-user-images.githubusercontent.com/81978191/348066752-248c3114-9f1c-4196-8fbc-43e62dd29d99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NTA3MjIsIm5iZiI6MTcyMDc1MDQyMiwicGF0aCI6Ii84MTk3ODE5MS8zNDgwNjY3NTItMjQ4YzMxMTQtOWYxYy00MTk2LThmYmMtNDNlNjJkZDI5ZDk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDAyMTM0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyZTZjZTlmNjFlYTgzMTdiNGM5NDNlMTBhMzM3YzAyNjJhMjU2YTE2NzA0MzNmNmMzNTU2N2E5NGY4ODI2YWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v1yTExcQP8_b_LTCgIG354LIeMDNT1VtO2DbJT5zwa4) lian'j链接向量数据库无法链接
