### ISSUE TITLE
部署完访问ui连接报错

### ISSUE THREAD

**Issue by xihuishawpy** [aigc-apps/PAI-RAG#118]
按照部署步骤部署的，报错：
![image](https://github.com/user-attachments/assets/10a00b3e-0197-4e83-b346-d3275e1d6d7d)

![image](https://github.com/user-attachments/assets/4c798333-3f5b-4898-a4f0-cce5578d63d5)

**Comment by moria97** [comment]
可以看下你启动ui的命令吗？或者直接试试
```sh
pai_rag ui -c http://127.0.0.1:8001
```

**Comment by xihuishawpy** [comment]
> 可以看下你启动ui的命令吗?或者直接试试
> 
> > > The shell
> pai _ rag ui - chttp://127.0.0.1:8001
> > > >

pai_rag ui - c http://127.0.0.1:8001 刚试过这个,还是一样报连接失败


之前启动ui的命令： pai_rag ui

**Comment by moria97** [comment]
浏览器访问地址是什么？

**Comment by xihuishawpy** [comment]
> 浏览器访问地址是什么？用127.0.0.1或者localhost，不要用0.0.0.0

浏览器访问的是：http://127.0.0.1:8002/

**Comment by moria97** [comment]
Close this issue
